use crate::traits::SubsonicAuthenticationTrait;
use crate::auth::{hash_password, SubsonicParameters};
use serde::Serialize;

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum OpenSubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
    Token {
        #[serde(rename = "apiKey")]
        api_key: Box<str>
    },
}

impl OpenSubsonicAuthentication {
    pub fn token(token: &str) -> Self {
        Self::Token { api_key: token.into() }
    }
}

impl SubsonicAuthenticationTrait for OpenSubsonicAuthentication {
    fn legacy_password(username: &str, password: &str) -> Self {
        Self::LegacyPassword { username: username.into(), password: password.into() }
    }
    fn hashed_password(username: &str, password: &str) -> Self {
        let (hashed_password, salt) = hash_password(password);

        Self::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        }
    }
}

impl SubsonicParameters<OpenSubsonicAuthentication> {
    /// Supported only by OpenSubsonic
    /// 
    /// Authenticate to OpenSubsonic with a token generated by the server
    pub fn token(client_name: &str, token: &str, version: &str) -> Self {
        let authentication = OpenSubsonicAuthentication::token(token);
        Self::new(client_name, version, authentication)
    }
}
