use rand::{distr::Alphanumeric, prelude::*};
use serde::Serialize;

fn hash_password(password: &str) -> (String, String) {
    let rng = rand::rng();
    let salt: String = rng.sample_iter(Alphanumeric)
        .take(64)
        .map(char::from)
        .collect();

    let salted_password = password.to_owned() + salt.as_str();
    let hashed_password = format!("{:x}", md5::compute(salted_password.as_bytes()));
    (hashed_password, salt)
}

pub trait SubsonicAuthenticationTrait {
    fn legacy_password(username: &str, password: &str) -> Self;
    fn hashed_password(username: &str, password: &str) -> Self;
}

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum SubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
}

impl SubsonicAuthenticationTrait for SubsonicAuthentication {
    fn legacy_password(username: &str, password: &str) -> Self {
        Self::LegacyPassword { username: username.into(), password: password.into() }
    }
    fn hashed_password(username: &str, password: &str) -> Self {
        let (hashed_password, salt) = hash_password(password);

        Self::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        }
    }
}

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum OpenSubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
    Token {
        #[serde(rename = "apiKey")]
        api_key: Box<str>
    },
}

impl OpenSubsonicAuthentication {
    pub fn token(token: &str) -> Self {
        Self::Token { api_key: token.into() }
    }
}

impl SubsonicAuthenticationTrait for OpenSubsonicAuthentication {
    fn legacy_password(username: &str, password: &str) -> Self {
        Self::LegacyPassword { username: username.into(), password: password.into() }
    }
    fn hashed_password(username: &str, password: &str) -> Self {
        let (hashed_password, salt) = hash_password(password);

        Self::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        }
    }
}

#[derive(Serialize, Debug)]
pub struct SubsonicParameters<T: SubsonicAuthenticationTrait> {
    #[serde(rename = "v")]
    version: Box<str>,
    #[serde(rename = "f")]
    format: Box<str>,
    #[serde(rename = "c")]
    client: Box<str>,
    #[serde(flatten)]
    authentication: T,
}

impl<T: SubsonicAuthenticationTrait> SubsonicParameters<T> {
    fn new(client_name: &str, version: &str, authentication: T) -> Self {
        Self {
            client: client_name.into(),
            version: version.into(),
            format: "json".into(),
            authentication,
        }
    }
    /// Use the legacy password authentication method with a clear text password
    pub fn legacy_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        // TODO implement hex-encoded variant
        let authentication = T::legacy_password(username, password);
        Self::new(client_name, version, authentication)
    }
    /// Supported since Subsonic 1.13.0
    ///
    /// Authenticate to Subsonic with a hashed password. Salt is generated inside the method. Uses
    /// md5
    pub fn hashed_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        let authentication = T::hashed_password(username, password);
        Self::new(client_name, version, authentication)
    }
}

impl SubsonicParameters<OpenSubsonicAuthentication> {
    /// Supported only by OpenSubsonic
    /// 
    /// Authenticate to OpenSubsonic with a token generated by the server
    pub fn token(client_name: &str, token: &str, version: &str) -> Self {
        let authentication = OpenSubsonicAuthentication::token(token);
        Self::new(client_name, version, authentication)
    }
}
