pub mod models;

use rand::{distr::Alphanumeric, prelude::*};
use serde::Serialize;
use thiserror::Error;
use crate::models::*;
use std::default::Default;

#[derive(Serialize, Debug)]
#[serde(untagged)]
enum SubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
    Token {
        #[serde(rename = "apiKey")]
        api_key: Box<str>
    }
}

#[derive(Serialize, Debug)]
pub struct SubsonicParameters {
    #[serde(rename = "v")]
    version: Box<str>,
    #[serde(rename = "f")]
    format: Box<str>,
    #[serde(rename = "c")]
    client: Box<str>,
    #[serde(flatten)]
    authentication: SubsonicAuthentication,
}

impl SubsonicParameters {
    fn new(client_name: &str, version: &str, authentication: SubsonicAuthentication) -> Self {
        Self {
            client: client_name.into(),
            version: version.into(),
            format: "json".into(),
            authentication,
        }
    }
    /// Use the legacy password authentication method with a clear text password
    pub fn legacy_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        // TODO implement hex-encoded variant
        let authentication = SubsonicAuthentication::LegacyPassword {
            username: username.into(),
            password: password.into(),
        };

        Self::new(client_name, version, authentication)
    }
    /// Supported since Subsonic 1.13.0
    ///
    /// Authenticate to Subsonic with a hashed password. Salt is generated inside the method. Uses
    /// md5
    pub fn hashed_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        let rng = rand::rng();
        let salt: String = rng.sample_iter(Alphanumeric)
            .take(64)
            .map(char::from)
            .collect();

        let salted_password = password.to_owned() + salt.as_str();
        let hashed_password = format!("{:x}", md5::compute(salted_password.as_bytes()));

        let authentication = SubsonicAuthentication::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        };

        Self::new(client_name, version, authentication)
    }
    /// Supported only by OpenSubsonic
    /// 
    /// Authenticate to OpenSubsonic with a token generated by the server
    pub fn token(client_name: &str, token: &str, version: &str) -> Self {
        let authentication = SubsonicAuthentication::Token { api_key: token.into() };
        Self::new(client_name, version, authentication)
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Search3Parameters {
    pub query: Box<str>,
    pub artist_count: u32,
    pub artist_offset: u32,
    pub album_count: u32,
    pub album_offset: u32,
    pub song_count: u32,
    pub song_offset: u32,
    pub music_folder_id: Option<Box<str>>,
}

impl Search3Parameters {
    pub fn query(query: &str) -> Self {
        Self {
            query: query.into(),
            ..Default::default()
        }
    }
}

impl Default for Search3Parameters {
    fn default() -> Self {
        Self {
            query: "".into(),
            artist_count: 20,
            artist_offset: 0,
            album_count: 20,
            album_offset: 0,
            song_count: 20,
            song_offset: 0,
            music_folder_id: None
        }
    }
}

#[derive(Serialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StarParameters {
    pub id: Option<Box<str>>,
    pub album_id: Option<Box<str>>,
    pub artist_id: Option<Box<str>>,
}

impl StarParameters {
    pub fn new(id: Option<&str>, album_id: Option<&str>, artist_id: Option<&str>) -> Self {
        Self {
            id: Some(id.unwrap_or_default().into()),
            album_id: Some(album_id.unwrap_or_default().into()),
            artist_id: Some(artist_id.unwrap_or_default().into()),
        }
    }
    pub fn id(id: &str) -> Self {
        Self { id: Some(id.into()), ..Default::default() }
    }
    pub fn album_id(album_id: &str) -> Self {
        Self { album_id: Some(album_id.into()), ..Default::default() }
    }
    pub fn artist_id(artist_id: &str) -> Self {
        Self { artist_id: Some(artist_id.into()), ..Default::default() }
    }
}

#[derive(Error, Debug)]
pub enum SubsonicError {
    #[error("There was an error during an HTTP request")]
    ReqwestError(#[from] reqwest::Error),
    #[error("Deserialization of a response failed")]
    SerdeError(#[from] serde_json::Error),
    #[error("The server returned a failed response")]
    Failed, // TODO actually contain any data from the server
}

pub struct Client {
    client: reqwest::Client,
    url: String,
    parameters: SubsonicParameters,
}

impl Client {
    /// A Client for the Subsonic API and OpenSubsonic
    pub fn new(url: &str, parameters: SubsonicParameters) -> Self {
        Self {
            client: reqwest::Client::new(),
            url: url.to_owned(),
            parameters,
        }
    }
    /// Used to test the connectivity with the server.
    pub async fn ping(&self) -> Result<BasicResponse, SubsonicError> {
        let url = self.url.clone() + "/rest/ping.view";
        let response = self.client.get(url)
            .query(&self.parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn search3(&self, parameters: Search3Parameters) -> Result<SearchResult3, SubsonicError> {
        let url = self.url.clone() + "/rest/search3.view";
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        // TODO fix the type mess
        let subsonic_response: SubsonicResponse<SearchResult3> = response.json().await?;

        if subsonic_response.subsonic_response.status != "ok".into() {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_response.subsonic_response.additional)
    }
    pub async fn star(&self, parameters: StarParameters) -> Result<BasicResponse, SubsonicError> {
        let url =  self.url.clone() + "/rest/star.view";
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn unstar(&self, parameters: StarParameters) -> Result<BasicResponse, SubsonicError> {
        let url =  self.url.clone() + "/rest/unstar.view";
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn get_song(&self, id: &str) -> Result<Song, SubsonicError> {
        let url = self.url.clone() + "/rest/getSong.view";
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&[("id", id)])
            .send()
            .await?;

        // TODO fix the type mess
        let subsonic_response: SubsonicResponse<Song> = response.json().await?;

        if subsonic_response.subsonic_response.status != "ok".into() {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_response.subsonic_response.additional)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct SubsonicLogin<'a> {
        url: &'a str,
        username: &'a str,
        password: &'a str,
    }

    // Navidrome Demo (OpenSubsonic)
    const NAVIDROME: SubsonicLogin = SubsonicLogin { 
        url: "https://demo.navidrome.org", 
        username: "demo", 
        password: "demo" 
    };

    // Subsonic Demo
    const SUBSONIC: SubsonicLogin = SubsonicLogin { 
        url: "http://demo.subsonic.org", 
        username: "guest4", 
        password: "guest" 
    };

    #[tokio::test]
    async fn ping() {
        // For Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let subsonic_client = Client::new(SUBSONIC.url, parameters);

        let ping_response_result = subsonic_client.ping().await;
        let ping_response = ping_response_result.unwrap();
        assert_eq!(ping_response.subsonic_response.status, "ok".into(), "{}", serde_json::to_string_pretty(&ping_response).unwrap());

        // For Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let subsonic_client = Client::new(NAVIDROME.url, parameters);

        let ping_response = subsonic_client.ping().await.unwrap();
        assert_eq!(ping_response.subsonic_response.status, "ok".into(), "{}", serde_json::to_string_pretty(&ping_response).unwrap());
    }

    #[tokio::test]
    async fn search3() {
        // For Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let subsonic_client = Client::new(SUBSONIC.url, parameters);

        let search3_response = subsonic_client.search3(Search3Parameters::query("A Million Ways To Waste A Summer")).await.unwrap();

        assert_eq!(search3_response.album.len(), 1, "{}", serde_json::to_string_pretty(&search3_response).unwrap());
        assert_eq!(search3_response.album[0].name, "A Million Ways To Waste A Summer", "{}", serde_json::to_string_pretty(&search3_response).unwrap());
    }

    #[tokio::test]
    async fn star_unstar_song() {
        // Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let client = Client::new(SUBSONIC.url, parameters);

        // Search Song
        let search3_response = client.search3(Search3Parameters::query("e")).await.unwrap();

        let song = search3_response.song[0].to_owned();
        let song_id = song.id;
        // Check if starred
        if song.starred.is_some() {
            // Unstar if starred
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

            // Star after unstarring
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");
        } else {
            // Star if unstarred
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");

            // Unstar after starring
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");
        }

        // Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let client = Client::new(NAVIDROME.url, parameters);

        // Search Song
        let search3_response = client.search3(Search3Parameters::query("")).await.unwrap();

        let song = search3_response.song[0].to_owned();
        let song_id = song.id;
        // Check if starred
        if song.starred.is_some() {
            // Unstar if starred
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

            // Star after unstarring
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");
        } else {
            // Star if unstarred
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");

            // Unstar after starring
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status, "ok".into());

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

        }
    }
}
