pub mod models;
pub mod parameters;

use rand::{distr::Alphanumeric, prelude::*};
use serde::de::DeserializeOwned;
use serde::Serialize;
use thiserror::Error;
use crate::models::*;
use crate::parameters::*;

fn hash_password(password: &str) -> (String, String) {
    let rng = rand::rng();
    let salt: String = rng.sample_iter(Alphanumeric)
        .take(64)
        .map(char::from)
        .collect();

    let salted_password = password.to_owned() + salt.as_str();
    let hashed_password = format!("{:x}", md5::compute(salted_password.as_bytes()));
    (hashed_password, salt)
}

pub trait SubsonicAuthenticationTrait {
    fn legacy_password(username: &str, password: &str) -> Self;
    fn hashed_password(username: &str, password: &str) -> Self;
}

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum SubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
}

impl SubsonicAuthenticationTrait for SubsonicAuthentication {
    fn legacy_password(username: &str, password: &str) -> Self {
        Self::LegacyPassword { username: username.into(), password: password.into() }
    }
    fn hashed_password(username: &str, password: &str) -> Self {
        let (hashed_password, salt) = hash_password(password);

        Self::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        }
    }
}

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum OpenSubsonicAuthentication {
    LegacyPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "p")]
        password: Box<str>,
    },
    HashedPassword {
        #[serde(rename = "u")]
        username: Box<str>,
        #[serde(rename = "t")]
        hashed_password: Box<str>,
        #[serde(rename = "s")]
        salt: Box<str>,
    },
    Token {
        #[serde(rename = "apiKey")]
        api_key: Box<str>
    },
}

impl OpenSubsonicAuthentication {
    pub fn token(token: &str) -> Self {
        Self::Token { api_key: token.into() }
    }
}

impl SubsonicAuthenticationTrait for OpenSubsonicAuthentication {
    fn legacy_password(username: &str, password: &str) -> Self {
        Self::LegacyPassword { username: username.into(), password: password.into() }
    }
    fn hashed_password(username: &str, password: &str) -> Self {
        let (hashed_password, salt) = hash_password(password);

        Self::HashedPassword { 
            username: username.into(), 
            hashed_password: hashed_password.into(), 
            salt: salt.into() 
        }
    }
}

#[derive(Serialize, Debug)]
pub struct SubsonicParameters<T: SubsonicAuthenticationTrait> {
    #[serde(rename = "v")]
    version: Box<str>,
    #[serde(rename = "f")]
    format: Box<str>,
    #[serde(rename = "c")]
    client: Box<str>,
    #[serde(flatten)]
    authentication: T,
}

impl<T: SubsonicAuthenticationTrait> SubsonicParameters<T> {
    fn new(client_name: &str, version: &str, authentication: T) -> Self {
        Self {
            client: client_name.into(),
            version: version.into(),
            format: "json".into(),
            authentication,
        }
    }
    /// Use the legacy password authentication method with a clear text password
    pub fn legacy_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        // TODO implement hex-encoded variant
        let authentication = T::legacy_password(username, password);
        Self::new(client_name, version, authentication)
    }
    /// Supported since Subsonic 1.13.0
    ///
    /// Authenticate to Subsonic with a hashed password. Salt is generated inside the method. Uses
    /// md5
    pub fn hashed_password(client_name: &str, username: &str, password: &str, version: &str) -> Self {
        let authentication = T::hashed_password(username, password);
        Self::new(client_name, version, authentication)
    }
}

impl SubsonicParameters<OpenSubsonicAuthentication> {
    /// Supported only by OpenSubsonic
    /// 
    /// Authenticate to OpenSubsonic with a token generated by the server
    pub fn token(client_name: &str, token: &str, version: &str) -> Self {
        let authentication = OpenSubsonicAuthentication::token(token);
        Self::new(client_name, version, authentication)
    }
}


#[derive(Error, Debug)]
pub enum SubsonicError {
    #[error("There was an error during an HTTP request")]
    ReqwestError(#[from] reqwest::Error),
    #[error("Deserialization of a response failed")]
    SerdeError(#[from] serde_json::Error),
    #[error("The server returned a failed response")]
    Failed, // TODO actually contain any data from the server
    #[error("Deserialization failed at {url} for {body}")]
    Deserialization { url: Box<str>, body: Box<str>, serde_error: serde_json::Error },
}

pub trait SubsonicServerInfo {
    type SubsonicAuthentication: Serialize + SubsonicAuthenticationTrait;
    type BasicResponse: DeserializeOwned;
    type SubsonicResponse<T: DeserializeOwned>: DeserializeOwned + SubsonicResponseTrait<T>;
}
pub struct Subsonic;
pub struct OpenSubsonic;

impl SubsonicServerInfo for Subsonic {
    type SubsonicAuthentication = SubsonicAuthentication;
    type BasicResponse = SubsonicBasicResponse;
    type SubsonicResponse<T: DeserializeOwned> = SubsonicResponse<T>;
}

impl SubsonicServerInfo for OpenSubsonic {
    type SubsonicAuthentication = OpenSubsonicAuthentication;
    type BasicResponse = OpenSubsonicBasicResponse;
    type SubsonicResponse<T: DeserializeOwned> = OpenSubsonicResponse<T>;
}

/// A Client for the Subsonic API and OpenSubsonic
pub struct Client<T: SubsonicServerInfo> {
    client: reqwest::Client,
    url: String,
    parameters: SubsonicParameters<T::SubsonicAuthentication>,
    phantom: std::marker::PhantomData<T>
}
pub type SubsonicClient = Client<Subsonic>;
pub type OpenSubsonicClient = Client<OpenSubsonic>;

impl<T: SubsonicServerInfo> Client<T> {
    pub fn new(url: &str, parameters: SubsonicParameters<T::SubsonicAuthentication>) -> Self {
        Self {
            client: reqwest::Client::new(),
            url: url.to_owned(),
            parameters,
            phantom: std::marker::PhantomData
        }
    }
    pub fn with_client(client: reqwest::Client, url: &str, parameters: SubsonicParameters<T::SubsonicAuthentication>) -> Self {
        Self {
            client,
            url: url.to_owned(),
            parameters,
            phantom: std::marker::PhantomData
        }
    }
    /// Used to test the connectivity with the server.
    pub async fn ping(&self) -> Result<T::BasicResponse, SubsonicError> {
        let url = format!("{}/rest/ping.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn get_license(&self) -> Result<License, SubsonicError> {
        let url = format!("{}/rest/getLicense.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .send()
            .await?;

        
        let subsonic_response: T::SubsonicResponse<License> = response.json().await?;
        let subsonic_data = subsonic_response.into_subsonic_data();

        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
    pub async fn search3(&self, parameters: Search3Parameters) -> Result<SearchResult3, SubsonicError> {
        let url = format!("{}/rest/search3.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        // TODO fix the type mess
        let url = response.url().to_owned();
        let response_text = response.text().await?;
        let subsonic_response: T::SubsonicResponse<SearchResult3> = match serde_json::from_str(&response_text) {
            Ok(success) => success,
            Err(error) => {
                return Err(SubsonicError::Deserialization { url: url.as_str().into(), body: response_text.into(), serde_error: error });
            }
        };

        let subsonic_data = subsonic_response.into_subsonic_data();
        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
    pub async fn star(&self, parameters: StarParameters) -> Result<T::BasicResponse, SubsonicError> {
        let url =  format!("{}/rest/star.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn unstar(&self, parameters: StarParameters) -> Result<T::BasicResponse, SubsonicError> {
        let url =  format!("{}/rest/unstar.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        Ok(response.json().await?)
    }
    pub async fn get_song(&self, id: &str) -> Result<Song, SubsonicError> {
        let url = format!("{}/rest/getSong.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&[("id", id)])
            .send()
            .await?;

        // TODO fix the type mess
        let subsonic_response: T::SubsonicResponse<Song> = response.json().await?;
        let subsonic_data = subsonic_response.into_subsonic_data();

        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
    pub async fn get_lyrics(&self, parameters: GetLyricsParameters) -> Result<Lyrics, SubsonicError> {
        let url = format!("{}/rest/getLyrics.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&parameters)
            .send()
            .await?;

        
        let subsonic_response: T::SubsonicResponse<Lyrics> = response.json().await?;
        let subsonic_data = subsonic_response.into_subsonic_data();

        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
}

impl Client<OpenSubsonic> {
    pub async fn get_lyrics_by_song_id(&self, id: &str) -> Result<LyricsList, SubsonicError> {
        // TODO write Tests
        // TODO account for OpenSubsonic Servers that don't implement the Extension
        let url = format!("{}/rest/getLyricsBySongId.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&[("id", id)])
            .send()
            .await?;

        
        let subsonic_response: OpenSubsonicResponse<LyricsList> = response.json().await?;
        let subsonic_data = subsonic_response.into_subsonic_data();

        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
    pub async fn get_lyrics_by_song_id_enhanced(&self, id: &str) -> Result<EnhancedLyricsList, SubsonicError> {
        // TODO write Tests
        // TODO account for OpenSubsonic Servers that don't implement the Extension
        let url = format!("{}/rest/getLyricsBySongId.view", self.url);
        let response = self.client.get(url)
            .query(&self.parameters)
            .query(&[("id", id), ("enhanced", "true")])
            .send()
            .await?;

        
        let subsonic_response: OpenSubsonicResponse<EnhancedLyricsList> = response.json().await?;
        let subsonic_data = subsonic_response.into_subsonic_data();

        if subsonic_data.status() != "ok" {
            return Err(SubsonicError::Failed);
        }

        Ok(subsonic_data.into_additional())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct SubsonicLogin<'a> {
        url: &'a str,
        username: &'a str,
        password: &'a str,
    }

    // Navidrome Demo (OpenSubsonic)
    const NAVIDROME: SubsonicLogin = SubsonicLogin { 
        url: "https://demo.navidrome.org", 
        username: "demo", 
        password: "demo" 
    };

    // Subsonic DemoI am
    const SUBSONIC: SubsonicLogin = SubsonicLogin { 
        url: "http://demo.subsonic.org", 
        username: "guest4", 
        password: "guest" 
    };

    #[tokio::test]
    async fn ping() {
        // For Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let subsonic_client = SubsonicClient::new(SUBSONIC.url, parameters);

        let ping_response_result = subsonic_client.ping().await;
        let ping_response = ping_response_result.unwrap();
        assert_eq!(ping_response.subsonic_response.status.as_ref(), "ok", "{:#?}", ping_response);

        // For Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let subsonic_client = OpenSubsonicClient::new(NAVIDROME.url, parameters);

        let ping_response = subsonic_client.ping().await.unwrap();
        assert_eq!(ping_response.subsonic_response.status.as_ref(), "ok", "{:#?}", ping_response);
    }

    #[tokio::test]
    async fn get_license() {
        // For Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let subsonic_client = SubsonicClient::new(SUBSONIC.url, parameters);

        let license = subsonic_client.get_license().await.unwrap();
        assert!(license.valid, "{:#?}", license);

        // For Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let subsonic_client = OpenSubsonicClient::new(NAVIDROME.url, parameters);

        let license = subsonic_client.get_license().await.unwrap();
        assert!(license.valid, "{:#?}", license);
    }

    #[tokio::test]
    async fn search3() {
        // For Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let subsonic_client = SubsonicClient::new(SUBSONIC.url, parameters);

        let search3_response = subsonic_client.search3(Search3Parameters::query("A Million Ways To Waste A Summer")).await.unwrap();

        assert_eq!(search3_response.album.len(), 1, "{:#?}", search3_response);
        assert_eq!(search3_response.album[0].name, "A Million Ways To Waste A Summer", "{:#?}", search3_response);
    }

    #[tokio::test]
    async fn star_unstar_song() {
        // Subsonic
        let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        let client = SubsonicClient::new(SUBSONIC.url, parameters);

        // Search Song
        let search3_response = client.search3(Search3Parameters::query("e")).await.unwrap();

        let song = search3_response.song[0].to_owned();
        let song_id = song.id;
        // Check if starred
        if song.starred.is_some() {
            // Unstar if starred
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

            // Star after unstarring
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");
        } else {
            // Star if unstarred
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");

            // Unstar after starring
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");
        }

        // Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let client = OpenSubsonicClient::new(NAVIDROME.url, parameters);

        // Search Song
        let search3_response = client.search3(Search3Parameters::query("")).await.unwrap();

        let song = search3_response.song[0].to_owned();
        let song_id = song.id;
        // Check if starred
        if song.starred.is_some() {
            // Unstar if starred
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

            // Star after unstarring
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");
        } else {
            // Star if unstarred
            let starred_response = client.star(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if starred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_some(), "Song should be starred after Star method was called");

            // Unstar after starring
            let starred_response = client.unstar(StarParameters::id(&song_id)).await.unwrap();
            assert_eq!(starred_response.subsonic_response.status.as_ref(), "ok");

            // Check if unstarred
            let song = client.get_song(&song_id).await.unwrap();
            assert!(song.starred.is_none(), "Song should be unstarred after Unstar method was called");

        }
    }

    #[tokio::test]
    async fn get_lyrics() {
        // TODO can't seem to get a response for any of these combinations
        // For Subsonic
        // let parameters = SubsonicParameters::hashed_password("subsonic rust", SUBSONIC.username, SUBSONIC.password, "1.16.0");
        // let subsonic_client = SubsonicClient::new(SUBSONIC.url, parameters);

        // Title Only
        // let get_lyrics_parameters = GetLyricsParameters::title("");
        // let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();

        // Artist Only
        // let get_lyrics_parameters = GetLyricsParameters::artist("");
        // let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();

        // Title and Artist
        // let get_lyrics_parameters = GetLyricsParameters::new("", "");
        // let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();

        // For Navidrome
        let parameters = SubsonicParameters::hashed_password("subsonic rust", NAVIDROME.username, NAVIDROME.password, "1.16.0");
        let subsonic_client = OpenSubsonicClient::new(NAVIDROME.url, parameters);

        // TODO can't seem to get a response for title only and artist only
        // Title Only
        // let get_lyrics_parameters = GetLyricsParameters::title("");
        // let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();

        // Artist Only
        // let get_lyrics_parameters = GetLyricsParameters::artist("");
        // let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();

        // Title and Artist
        let get_lyrics_parameters = GetLyricsParameters::new("Nine Inch Nails", "Letting You");
        let get_lyrics_response = subsonic_client.get_lyrics(get_lyrics_parameters).await.unwrap();
        assert_eq!(get_lyrics_response.title, "Letting You".into(), "The titles don't match for Navidrome Title and Artist");
        assert_eq!(get_lyrics_response.artist, "Nine Inch Nails".into(), "The artists don't match for Navidrome Title and Artist");
        assert!(!get_lyrics_response.value.is_empty(), "Lyrics should not be empty for Navidrome Title and Artist");
    }
}
